services:
  gem:
    build:
      target: test
      context: .
    volumes:
      - ./:/opt
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8808:8808"
    command: ["tail", "-f", "/dev/null"]
  rabbitmq:
    image: rabbitmq:3.9.29-management
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "15672:15672"
  payments:
    build:
      context: examples/payments
    volumes:
      - ./examples/payments:/rails
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    command: ["./bin/rails", "s", "-b", "0.0.0.0"]
  payments-subscriber:
    build:
      context: examples/payments
    volumes:
      - ./examples/payments:/rails
    environment:
      - SECRET_KEY_BASE=a_secret_key_base
    command: ["bundle", "exec", "harmoniser"]

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - rabbitmq
    command: rabbitmq:5672
