name: Harmoniser Release

on:
  push:
    branches: [ "master" ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.2.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"

    - name: Get version from gemspec
      id: get_version
      run: echo "VERSION=$(ruby -e 'puts Gem::Specification.load("harmoniser.gemspec").version')" >> $GITHUB_ENV

    - name: Create and Push Git Tag
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git tag v$VERSION
        git push origin v$VERSION
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
